server:
  port: 8002

spring:
  application:
  mvc:
    static-path-pattern: /static/**
    static-locations: file:/resources/static
    add-mappings: true
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB